### ISSUE TITLE
VSStudio on MacOS has a problem with the nuget package

### ISSUE THREAD

**Issue by thomasd3** [nessos/FsPickler#121] opened 2020-08-26 16:09 UTC
I have a project that includes the nuget package.

With Rider, everything works well, but with VSStudio MacOS I get this:

`Error FS0229: Error opening binary file '/Users/thomas/.nuget/packages/fspickler/5.3.2/lib/netstandard2.0/FsPickler.dll': Error reading/writing metadata for the F# compiled DLL '/Users/thomas/.nuget/packages/fspickler/5.3.2/lib/netstandard2.0/FsPickler.dll'. Was the DLL compiled with an earlier version of the F# compiler? (error: 'lookup_uniq in table istrings out of range, n = 115, sizeof(tab) = 1'). (FS0229) (Common2)`

Would it be possible refresh the nuget package to see if it solves the problem?

**Comment by eiriktsarpalis** [comment] 2020-08-27 07:48
Duplicate of #120, you need a newer of the F# compiler to consume the latest version.

**Closed as completed by eiriktsarpalis** 2020-08-27 07:48 UTC
